GET http://localhost:5001/api/measurement

###

GET http://localhost:5001/api/measurement/1

###

GET http://localhost:5001/api/measurement/1

###

DELETE http://localhost:5001/api/measurement/10

###

POST http://localhost:5001/api/measurement
Content-Type: application/json

{
        "name": "Measurement_999",
        "value": 0.06,
        "createdBy": "Operator 1",
        "createdAt": "2019-04-03T00:00:00"
}